CREATE TABLE IF NOT EXISTS control_cerco (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tramo VARCHAR(100) NOT NULL,
  roja_si TINYINT(1) DEFAULT 0,
  roja_no TINYINT(1) DEFAULT 0,
  verde_si TINYINT(1) DEFAULT 0,
  verde_no TINYINT(1) DEFAULT 0,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

